INSERT INTO challenges (id, category, theme, description, points) VALUES
(110, 'general', '🌟 Personal Growth', 'Set aside 30 minutes to reflect on your long-term goals and progress', 0),
(109, 'general', '🌟 Personal Growth', 'Practice a new technique for improving focus or productivity', 0),
(108, 'general', '🌟 Personal Growth', 'Review and update your personal mission statement or life goals', 0),
(107, 'general', '🌟 Personal Growth', 'Write about a recent learning experience and its impact on you', 0),
(106, 'general', '🌟 Personal Growth', 'Create a list of qualities you admire in others and how you can cultivate them', 0),
(105, 'general', '🌟 Personal Growth', 'Spend 20 minutes researching a new skill you''d like to develop', 0),
(104, 'general', '🌟 Personal Growth', 'Identify a personal habit to work on and make a plan for improvement', 0),
(103, 'general', '🌟 Personal Growth', 'Reflect on a recent achievement and what it means to you', 0),
(102, 'general', '🌟 Personal Growth', 'Set a small personal goal and create an action plan for it', 0),
(101, 'general', '🌟 Personal Growth', 'Read a chapter of a self-improvement book', 0),
(100, 'general', '🧑‍🤝‍🧑 Social Connection', 'Offer help or support to someone in need', 0),
(99,  'general', '🧑‍🤝‍🧑 Social Connection', 'Participate in a discussion group or forum about a topic of interest', 0),
(98,  'general', '🧑‍🤝‍🧑 Social Connection', 'Volunteer for a community project or event', 0),
(97,  'general', '🧑‍🤝‍🧑 Social Connection', 'Share a positive post or story on social media', 0),
(96,  'general', '🧑‍🤝‍🧑 Social Connection', 'Engage in a group activity or hobby online', 0),
(95,  'general', '🧑‍🤝‍🧑 Social Connection', 'Write a letter to a friend and mail it', 0),
(94,  'general', '🧑‍🤝‍🧑 Social Connection', 'Invite someone to a coffee or lunch (virtually or in person)', 0),
(93,  'general', '🧑‍🤝‍🧑 Social Connection', 'Attend a virtual event or social gathering', 0),
(92,  'general', '🧑‍🤝‍🧑 Social Connection', 'Send a thoughtful message to a colleague or family member', 0),
(91,  'general', '🧑‍🤝‍🧑 Social Connection', 'Call or video chat with a friend you haven''t spoken to in a while', 0),
(90,  'general', '🧩 Creativity',             'Create a vision board for your dreams and aspirations', 0),
(89,  'general', '🧩 Creativity',             'Write a letter to your future self with creative prompts', 0),
(88,  'general', '🧩 Creativity',             'Take a photo of something that inspires you and write about it', 0),
(87,  'general', '🧩 Creativity',             'Design a personal logo or symbol that represents you', 0),
(86,  'general', '🧩 Creativity',             'Compose a piece of music or create a playlist that reflects your emotions', 0),
(85,  'general', '🧩 Creativity',             'Try a new craft or DIY project for 30 minutes', 0),
(84,  'general', '🧩 Creativity',             'Make a scrapbook page about a recent event', 0),
(83,  'general', '🧩 Creativity',             'Create a new recipe or dish and try it out', 0),
(82,  'general', '🧩 Creativity',             'Write a short story or poem about an imaginary world', 0),
(81,  'general', '🧩 Creativity',             'Draw or paint something that represents your mood', 0),
(80,  'general', '🙏 Gratitude',             'Write a letter to your past self expressing gratitude for lessons learned', 0),
(79,  'general', '🙏 Gratitude',             'Create a gratitude collage or vision board', 0),
(78,  'general', '🙏 Gratitude',             'Write about a time when someone''s kindness made a difference to you', 0),
(77,  'general', '🙏 Gratitude',             'Make a list of five things you appreciate about your life', 0),
(76,  'general', '🙏 Gratitude',             'Express your appreciation to a friend or family member in person', 0),
(75,  'general', '🙏 Gratitude',             'Write down three positive things that happened today', 0),
(74,  'general', '🙏 Gratitude',             'Create a gratitude jar and add a note to it', 0),
(73,  'general', '🙏 Gratitude',             'Share a compliment with someone you appreciate', 0),
(72,  'general', '🙏 Gratitude',             'Spend 10 minutes reflecting on things you''re grateful for', 0),
(71,  'general', '🙏 Gratitude',             'Write a thank-you note to someone who helped you', 0),
(70,  'exercise', NULL,                       'Do a 20-minute high-intensity interval training (HIIT) session', 0),
(69,  'exercise', NULL,                       'Join a fitness class or group activity for 30 minutes', 0),
(68,  'exercise', NULL,                       'Go for a bike ride for 30 minutes', 0),
(67,  'exercise', NULL,                       'Do a 15-minute bodyweight workout', 0),
(66,  'exercise', NULL,                       'Dance to your favorite music for 20 minutes', 0),
(65,  'exercise', NULL,                       'Engage in a sport you enjoy for 30 minutes', 0),
(64,  'exercise', NULL,                       'Practice yoga or stretching for 20 minutes', 0),
(63,  'exercise', NULL,                       'Try a new physical activity for 30 minutes', 0),
(62,  'exercise', NULL,                       'Do a 20-minute workout at home', 0),
(61,  'exercise', NULL,                       'Go for a 30-minute walk or jog', 0),
(60,  'journaling', NULL,                     'Journal about what brings you joy and why', 0),
(59,  'journaling', NULL,                     'Describe a perfect day in your ideal future', 0),
(58,  'journaling', NULL,                     'Reflect on a personal value and how you practiced it today', 0),
(57,  'journaling', NULL,                     'Write a poem about a subject that interests you', 0),
(56,  'journaling', NULL,                     'Create a list of things you want to try or learn', 0),
(55,  'journaling', NULL,                     'Write about a book or movie that impacted you recently', 0),
(54,  'journaling', NULL,                     'Detail a challenge you overcame and how', 0),
(53,  'journaling', NULL,                     'Write about your biggest accomplishment this year', 0),
(52,  'journaling', NULL,                     'Describe a recent act of kindness you witnessed', 0),
(51,  'journaling', NULL,                     'Create a list of your favorite quotes', 0),
(50,  'journaling', NULL,                     'Write about a person who inspires you and why', 0),
(49,  'journaling', NULL,                     'List five personal strengths', 0),
(48,  'journaling', NULL,                     'Express your thoughts on a current event', 0),
(47,  'journaling', NULL,                     'Write a letter to your future self', 0),
(46,  'journaling', NULL,                     'Describe your ideal day in detail', 0),
(45,  'journaling', NULL,                     'Set a small goal for tomorrow and write about it', 0),
(44,  'journaling', NULL,                     'Reflect on a recent challenge and what you learned', 0),
(43,  'journaling', NULL,                     'Write about a positive experience from today', 0),
(42,  'journaling', NULL,                     'List three things you''re grateful for today', 0),
(41,  'journaling', NULL,                     'Write a page about your day', 0),
(40,  'sleep',      NULL,                     'Try using a sleep mask if you are sensitive to light', 0),
(39,  'sleep',      NULL,                     'Limit liquid intake before bed to avoid waking up', 0),
(38,  'sleep',      NULL,                     'Establish a pre-sleep routine that includes a relaxing activity', 0),
(37,  'sleep',      NULL,                     'Create a sleep-friendly environment by decluttering your bedroom', 0),
(36,  'sleep',      NULL,                     'Avoid intense exercise within 2 hours of bedtime', 0),
(35,  'sleep',      NULL,                     'Go to bed at least 30 minutes earlier than usual', 0),
(34,  'sleep',      NULL,                     'Practice yoga stretches to relax your body before sleep', 0),
(33,  'sleep',      NULL,                     'Try a calming herbal tea before bed', 0),
(32,  'sleep',      NULL,                     'Write down worries and concerns in a journal before bed', 0),
(31,  'sleep',      NULL,                     'Avoid napping during the day to improve nighttime sleep', 0),
(30,  'sleep',      NULL,                     'Try progressive muscle relaxation before sleep', 0),
(29,  'sleep',      NULL,                     'Use a white noise machine or app if needed', 0),
(28,  'sleep',      NULL,                     'Practice deep breathing exercises before bed', 0),
(27,  'sleep',      NULL,                     'Read a book for 30 minutes before sleeping', 0),
(26,  'sleep',      NULL,                     'Avoid heavy meals and alcohol close to bedtime', 0),
(25,  'sleep',      NULL,                     'Limit caffeine intake after 2 PM', 0),
(24,  'sleep',      NULL,                     'Keep your room dark and quiet for better sleep', 0),
(23,  'sleep',      NULL,                     'Avoid screens for at least an hour before bed', 0),
(22,  'sleep',      NULL,                     'Create a relaxing bedtime routine and follow it', 0),
(21,  'sleep',      NULL,                     'Sleep for at least 9 hours today', 0),
(20,  'meditation', NULL,                     'Try a meditation focused on self-compassion for 10 minutes', 0),
(19,  'meditation', NULL,                     'Meditate with your eyes closed for 15 minutes', 0),
(18,  'meditation', NULL,                     'Practice mindful breathing during a daily task', 0),
(17,  'meditation', NULL,                     'Focus on a single thought for 10 minutes', 0),
(16,  'meditation', NULL,                     'Use a meditation timer for 20 minutes', 0),
(15,  'meditation', NULL,                     'Meditate in the morning before starting your day', 0),
(14,  'meditation', NULL,                     'Practice meditation before bedtime for 15 minutes', 0),
(13,  'meditation', NULL,                     'Try a new meditation technique for 15 minutes', 0),
(12,  'meditation', NULL,                     'Do a 10-minute visualization meditation', 0),
(11,  'meditation', NULL,                     'Practice mindful listening for 10 minutes', 0),
(10,  'meditation', NULL,                     'Meditate with a focus on gratitude for 10 minutes', 0),
(9,   'meditation', NULL,                     'Try a walking meditation for 15 minutes', 0),
(8,   'meditation', NULL,                     'Use a mantra during meditation for 10 minutes', 0),
(7,   'meditation', NULL,                     'Practice loving-kindness meditation for 10 minutes', 0),
(6,   'meditation', NULL,                     'Meditate in nature for 15 minutes', 0),
(5,   'meditation', NULL,                     'Focus on your breath for 10 minutes', 0),
(4,   'meditation', NULL,                     'Do a 5-minute body scan meditation', 0),
(3,   'meditation', NULL,                     'Practice mindfulness while eating one meal', 0),
(2,   'meditation', NULL,                     'Try a guided meditation app for 10 minutes', 0),
(1,   'meditation', NULL,                     'Meditate for at least 15 minutes today', 0);
